// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKR7Z03Hjm-yLArsNN1pxy5DXDRq1TS68',
    appId: '1:594252193689:web:a455cd8ae00b01c6a3bd08',
    messagingSenderId: '594252193689',
    projectId: 'drive-clone-60440',
    authDomain: 'drive-clone-60440.firebaseapp.com',
    storageBucket: 'drive-clone-60440.appspot.com',
    measurementId: 'G-6FHGRZSSFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa7YSxh_Q87k_DWoW1xNN0HLlMfK9VO7w',
    appId: '1:594252193689:android:883f8449a68ec6efa3bd08',
    messagingSenderId: '594252193689',
    projectId: 'drive-clone-60440',
    storageBucket: 'drive-clone-60440.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvw8tcWpbtJdD_WQHJZcbWaYCUM2gPrYM',
    appId: '1:594252193689:ios:a5b2b409769438aaa3bd08',
    messagingSenderId: '594252193689',
    projectId: 'drive-clone-60440',
    storageBucket: 'drive-clone-60440.appspot.com',
    iosBundleId: 'com.example.drive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvw8tcWpbtJdD_WQHJZcbWaYCUM2gPrYM',
    appId: '1:594252193689:ios:2130b0d3417394a1a3bd08',
    messagingSenderId: '594252193689',
    projectId: 'drive-clone-60440',
    storageBucket: 'drive-clone-60440.appspot.com',
    iosBundleId: 'com.example.drive.RunnerTests',
  );
}
